### ISSUE TITLE
Include ide-reason in list of Atom Packages

### ISSUE THREAD

**Issue by rickyvetter** [atom/atom-languageclient#103]
[The wiki](https://github.com/atom/atom-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient) doesn't currently mention [ide-reason](https://github.com/zaaack/atom-ide-reason). It would be great to include it in the listings, especially since it's linked to as the canonical list from the [recent Nuclide blog post](https://nuclide.io/blog/2017/09/12/Introducing-Atom-IDE-UI/) about Atom IDE.

I was going to add it myself but it looks like the edit permissions are not open right now.

**Comment by damieng** [comment]
Thanks for putting together your package!  

I'm putting together a new list that will replace the wiki and the contents of the README.

One of the things we want to do is ensure that all the libraries we list are running the latest atom-languageclient because of various fixes and that they are set to use Atom 1.21 (currently beta) as earlier versions do not include proper file-change tracking or give the language server enough time to cleanly shut-down.

Is it possible you could make those changes to your package?

**Comment by rickyvetter** [comment]
We'll look into making the changes. Shouldn't be a problem. To clarify that means that it should work with `atom-languageclient` v0.6.1 running in Atom 1.21? Is there a list of changes to look out for?

**Comment by damieng** [comment]
There haven't been any breaking changes yet as far as I remember although things have been a bit hectic.

If your language server starts up and is doing things you're probably good to go.

**Comment by keyvhinng** [comment]
Hi, I just want to mention Typescript link is wrong on Wiki's List of Atom packages. Currently is https://github.com/ide-typescript but it should be https://github.com**/atom**/ide-typescript
