### ISSUE TITLE
workspace/didChangeConfiguration

### ISSUE THREAD

**Issue by JakeBecker** [atom/atom-languageclient#123]
The spec is the same in v2 and v3 of the Language Server Protocol: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_didChangeConfiguration

In VS Code, the IDE send this notification immediately after initialization and any time it changes.

**Comment by lgeiger** [comment]
You could do this quite easily by [observing the package settings in the `postInitialization` hook](https://github.com/lgeiger/ide-python/blob/master/lib/main.js#L21). This is how we're using it in the  `ide-python` package.

**Comment by damieng** [comment]
I think as @lgeiger this is quite package specific - at least the ide-* packages I've created the package settings are used as part of the start-up process rather than sent to the remote end. 

If we can come up with a convention we could auto-send them though.

I'm open to suggestions (and PRs) ;-)

**Comment by JakeBecker** [comment]
@lgeiger's approach worked great, and it's straightforward enough that I think it's probably not necessary to have another solution. My only suggestion would be to document it somewhere. I'm going to close this issue.

Thanks!
