### ISSUE TITLE
textDocument/rename

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#13]
The [textDocument/rename](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_rename) protocol lets you rename a symbol and automatically update all associated symbols.

We could implement this with a command and a right-menu button but it would also need a ui for the new symbol unless we could do it inline.

**Comment by hansonw** [comment]
We've got a UI for that in Nuclide as well. It's a tad heavyweight (since it's designed to support more complex refactorings) so I'm not sure if you'd want to start from there or start afresh.

https://github.com/facebook/nuclide/blob/master/pkg/nuclide-refactorizer

The basic flow is right click a symbol, click Refactor in the context menu, select rename, and then type in a new name. There's also an explicit command for quickly just renaming.

**Comment by lierdakil** [comment]
What's the status on this? Minimal implementation should be doable in less than 100 lines... For instance, https://github.com/atom-haskell/hie-lsp-adapter/blob/master/lib/main.js#L20

**Comment by arxanas** [comment]
See also https://github.com/facebook-atom/atom-ide-ui/issues/145#issuecomment-412589283

**Comment by BenjaminNavarro** [comment]
I'm not very familiar with Atom extensions development but I'd like to contribute to this issue. Any tips on where to start?
