### ISSUE TITLE
Implement request cancellation ($/cancelRequest)

### ISSUE THREAD

**Issue by daviwil** [atom/atom-languageclient#140]
Spec: [`$/cancelRequest`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#cancelRequest)

vscode-jsonrpc provides a [`CancellationToken`](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/cancellation.ts#L16) type which we could potentially re-expose through atom-languageclient.  We'd have to wire up a CancellationToken parameter on `LanguageClientConnection._sendRequest` and add one as an optional parameter to any method that calls it.  Luckily the RPC library [takes care of](https://github.com/Microsoft/vscode-languageserver-node/blob/6a3986aecac325361db4cc8a137415fd3b8337cb/jsonrpc/src/main.ts#L969) sending the `$/cancelRequest` notification if a CancellationToken gets cancelled.

**Comment by damieng** [comment]
I think we'd want to automatically cancel them in autolanguageclient when we get a subsequent request for another one that would make the previous one useless. e.g. autocomplete, outline view, hover, signature help, definitions.

Probably not for some others though like find all references.

**Comment by daviwil** [comment]
Sounds good!  I suppose the `LanguageClientConnection` wrapper methods are the right place to do that?

**Comment by damieng** [comment]
They'll need to return the cancellationToken but we'll probably need to keep the most recent for the ones that auto cancel either on the instance of the adapter or somewhere else that we can track on a per-server basis.

This might be time to make all the adapters server-instance instead of the current sharing etc. they do.

The alternative is to track them on AutoLanguageClient but I fear it's a bit of a dumping ground.

**Comment by hansonw** [comment]
We've actually been thinking about adding some sort of cancellation token mechanism to atom-ide-ui's APIs so that they can just be directly forwarded over. Google just decided to implement abortable fetches in Chrome so it may not look exactly like VSCode's `CancellationToken`, but it should be easily adaptable. https://developers.google.com/web/updates/2017/09/abortable-fetch

cc @matthewwithanm

**Comment by daviwil** [comment]
Status update: Damien and I decided to put this one on hold until we can decide on the right way to expose cancellation from the atom-languageclient APIs.  The choices are between exposing vscode-jsonrpc's CancellationToken type all the way up through the API and services (not that desirable) or implementing some form of CancellablePromise which wraps their CancellationToken.
