### ISSUE TITLE
When adding "atom-languageclient" as dependency as stated in README.md, "apm install" will add a copy to node_modules/ with no "lib" or "build" which is hence unimportable

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#16]
Warning: this might be due to a fundamental misunderstanding of node.js / npm on my side.

I tried the following things:
1. I made a new custom package closely following the README.md example code and the java language client atom package
2. I added "atom-languageclient" as dependency
3. I used `apm install` to install the resulting package

The following happened:
1. The package was copied into ~/.atom/packages/<package>
2. A subfolder was created `~/.atom/packages/<package>/node_modules`
3. There is now the dependency atom-languageclient inside `~/.atom/packages/<package>/node_modules/atom-languageclient`... but with no "build" folder which the main entry point in the package.json refers to, hence it's unimportable and my package doesn't actually work. Even more confusingly, the atom-languageclient version in that folder also lacks "lib" so running `npm run compile .` doesn't even allow me to actually build it.

What I expected instead is that `apm install` would also give me a working copy of `atom-languageclient` nested inside my custom package attempt so that things actually work.

**Comment by hansonw** [comment]
Sorry about this! I'll fix this ASAP (this is due to https://github.com/npm/npm/issues/3055)

**Comment by damieng** [comment]
Yeah sorry @JonasT originally we checked in the transpiled flow source under the build folder but we changed from that behavior recently which has broken the pull-from-git model which @hansonw is fixing.

As a temporary measure you can check out the atom-languageclient repo and then `npm link .` inside the folder. Finally `npm link atom-languageclient` inside your repo.

**Comment by lloiser** [comment]
Is there any reason why we need this compilation step at all? atom is able to "transpile" the code without any problems.

**Comment by damieng** [comment]
The Atom transpilation only works for the project itself unfortunately - not apm package dependencies such as this.

**Comment by damieng** [comment]
This will be a total non-issue once atom-languageclient is published to npm - you're just very early to this party :)

**Comment by lloiser** [comment]
> The Atom transpilation only works for the project itself unfortunately 

I thought it also works for the `node_modules`. So `require('atom-languageclient')` would cause the atom-languageclient to be transpiled. At least I can see in the dev tools that all files go through [`atom/src/babel.js#L22`](https://github.com/atom/atom/blob/master/src/babel.js#L22).

I will see if I can get this running without the build step.

**Comment by hansonw** [comment]
@lloiser Just committed the fix, please try again. Although it may be possible to get Atom's transpiler to work (I believe we rely on it when developing for Nuclide) it's not a good idea:

1) on-the-fly transpilation is intended for development use and comes with a nontrivial startup overhead
2) Atom's transpilation settings may not match up exactly and it's hard to consolidate those.

**Comment by BinaryMuse** [comment]
@damieng is correct; there's Atom's *built in* Babel pipeline (`atom/src/babel.js`) which is kicked into effect when you `'use babel'` at the top of JS files, and there's the custom transpiler setup which this project uses. This only works for packages. This repo is a bit of an odd case because it's not a package, but it's being treated as one for purposes of tests (AFAICT).

For npm packages, the proper solution is to pre-transpile the files and push them to the npm registry. `.gitignore` and `.npmignore` allows you to specify which files live in both the repo and the registry, while the Atom registry does not allow this. Worth noting, perhaps, that we'd *like* it to, and we would prefer that people pre-transpiled their Atom packages just like you do for npm packages — we just don't have the infrastructure for that yet.
