### ISSUE TITLE
Deal with multiple project folders

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#19]
The LSP protocol requires you initialize with a root path or url it can start examining.

What do we do about Atom projects/workspaces with multiple project folders?

## Options

1. Nothing - a lot of stuff would appear to be broken
2. Fire up an LSP for each folder
...

**Comment by hansonw** [comment]
2) has worked well for us in Nuclide. However I think it's important to have some concept of a "project root" that's separate from the Atom concept of a project, since you might multiple subdirectories of a project and expect them to share a LS.

Nuclide language servers enforce a well-defined "project file" that we use to resolve the root. For Hack and Flow this is a `.hhconfig` / `.flowconfig` file, for example. And `package.json` might be a sensible default for vanilla JS projects.

It may or may not make sense to build this concept into the `AutoLanguageClient`?

our implementation: https://github.com/facebook/nuclide/blob/0264b4ecc0129eef1d2268863eac788656570f6f/pkg/nuclide-language-service-rpc/lib/MultiProjectLanguageService.js#L51

**Comment by damieng** [comment]
Now working.
