### ISSUE TITLE
Nuclide diagnostics should highlight word if range length is zero

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#22]
Right now some linters and language servers return a range length of zero.

We should detect this and highlight the entire word/symbol under the cursor.

**Comment by Arcanemagus** [comment]
You can get the scope specific RegEx for this from Atom with something similar to this: [`getWordRegexp](https://github.com/steelbrain/atom-linter/blob/1f95edbad2eebd261c5224288a32a2f1815c1e3d/src/helpers.js#L19).

That's what we currently use for linter providers when only given a line/column.

**Comment by hansonw** [comment]
This works now! https://github.com/facebook/nuclide/commit/be4ae526fc2d7c8c5101803b287783f94161d776

**Comment by Arcanemagus** [comment]
Just a note @hansonw that the method in that commit will fail for multi-scoped files (think things like PHP inside HTML) if the user has their cursor in the "wrong" scope for the desired section.

**Comment by damieng** [comment]
Thanks @hansonw

**Comment by damieng** [comment]
@Arcanemagus Not sure I understand the error - can you clarify?

**Comment by Arcanemagus** [comment]
That commit [uses](https://github.com/facebook/nuclide/commit/be4ae526fc2d7c8c5101803b287783f94161d776#diff-bcb08e223f95130ce963edf9d6bdaa34R107) `wordAtPosition` which is defined [here](https://github.com/facebook/nuclide/blob/master/pkg/commons-atom/range.js#L14). That function when you don't feed it an override regex uses the last cursor's `wordRegExp` [here](https://github.com/facebook/nuclide/blob/master/pkg/commons-atom/range.js#L21).

The issue is that the last cursor can be in an entirely different scope from the buffer position requested. However, when I was trying to actually replicate a case where that would pose problems yesterday so I could file an issue there so that gets fixed I wasn't able to find a case where the scope chain gave a different result for different parts of the file. It should be a possibility, the example I gave (and JS within Markdown) don't actually trigger it. I'll have to look through the languages to see if it's actually a problem in real usage.

(The code I linked before uses the scope at the requested buffer position to get the proper regex, instead of using the last cursor so it avoids this issue even in any possible case.)

**Comment by hansonw** [comment]
Ah good point.. yeah I guess we should construct the regexp manually with
the scope descriptor at the given position. As you mentioned though, this
doesn't tend to be practically noticeable (at least so far we've never had
any internal reports of badly selected ranges at Facebook).

I'll file a follow-up task to do this the right way.
