### ISSUE TITLE
I am often only getting a request header (with Content-Length) and no contents

### ISSUE THREAD

**Issue by JonasT** [atom/atom-languageclient#24]
Hi, with my first test binary as a language server I am often only getting a request header (with Content-Length specified and the following \n\n line breaks) and no contents on stdin. It seems almost like it is line break or even block buffered and atom-languageclient doesn't flush the stdin pipe after a request so it's stuck somewhere in between in buffer limbo.

I tried everything I know to get rid of the buffering on my side (I'm using Python 3) but it's hard to test since in a terminal it behaves differently due to the way the libc operates. However, I believe a flush on the sending side (atom-languageclient) could easily fix this too.

Is there any chance you could add more aggressive pipe flushing after requests to prevent stuff getting stuck in buffering when sent through atom-languageclient --stdin--> language-server?

**Comment by JonasT** [comment]
For what it's worth, sometimes when I click around in Atom for a while (multiple minutes) the end of the request arrives and another half-finished followup request comes in and it stops again, presumably because of the same problem..

**Comment by damieng** [comment]
All the low-level communication is handled by the vscode-jsonrpc library so we have no control over flushing/batching etc. I would be very surprised if the library on this side has problems as it has been in use in Visual Studio Code and their language servers for many months.

How are you reading the data on the python side? There seem to be a couple of json-rpc libraries for python available that might be worth trying. Additionally you could look at using a network port rather than using stdin/stdout.

An example of how to do that on the Atom side can be found in the php language sever at https://github.com/atom/languageserver-php/blob/master/lib/main.js

**Comment by JonasT** [comment]
My language server does support sockets, but I don't understand the code you linked. It seems in that code, the atom-languageclient itself runs as a server(?) or launches a listener socket for some other reason. So if there is some code around that shows how to connect to a language server that has opened a listen port via TCP, that would be very helpful since my node.js knowledge is a bit limited.

**Comment by damieng** [comment]
The code I linked creates a fake network server just to find an available free port and socket. It then starts the actual language server using spawnserver passing the port number on the command line and using the socket to pass through to vscode-jsonrpc to connect to it.

**Comment by damieng** [comment]
For development purposes you could probably just hard-code a port number and avoid a lot of that code.

**Comment by JonasT** [comment]
@damieng I did now dig a bit into node.js networking and switch to a TCP port, and the problem is gone. Thanks for the idea, and I'll close this assuming I broke something about stdin/stdout since it works for everyone else.
