### ISSUE TITLE
Race condition with document changes and autocomplete requests

### ISSUE THREAD

**Issue by hansonw** [atom/atom-languageclient#29]
Currently, typing a character will issue the autocomplete request before the `document/didChange` message goes through. This is because we're using `onDidStopChanging` to transmit buffer changes, so there's a ~300ms debounce (while autocomplete requests have a 100ms debounce).

I think @wbinnssmith mentioned this already, but should we just go back to using `onDidChange`?

**Comment by damieng** [comment]
I was going to speak to @maxbrunsfeld about this - it would be great if we could flush the changes out when we make an autocomplete request.

**Comment by maxbrunsfeld** [comment]
Can we just use `onDidChangeText` instead of `onDidStopChanging`? I think it behaves the exact same way, except that it fires once per transaction instead of every 300ms.

**Comment by maxbrunsfeld** [comment]
We *can* retrieve the changes since the last `onDidStopChanging` event by calling `buffer.createCheckpoint()` in the event handler and then calling `getChangesSinceCheckpoint` when making an autocomplete request, but that will introduce some complexity because the next time the `onDidStopChangingEvent` fires, we will have already synced *some* of those changes.

**Comment by hansonw** [comment]
@maxbrunsfeld Yep we will switch from `onDidChange` as soon as 1.17 becomes stable :) We need the `oldText` field, which was only added recently (see https://github.com/atom/text-buffer/pull/223)
