### ISSUE TITLE
Hover (DataTip) requests are received by LS for non-applicable resources

### ISSUE THREAD

**Issue by BoykoAlex** [atom/atom-languageclient#67]
I have a LS package for Atom for `*manifest*.yml` files.
Project has `manifest.yml` file opened in an editor, my LS is started and i can see data tips shown when hovering on keywords provided by `atom-ide-ui` package.
If I open `.classpath` file or `pom.xml` file or any other from the same project (probably any arbitrary file from the project) then my LS for `manifest.yml` files starts receiving hover requests for stuff from the file opened above which is not the `*manifest*.yml` file.

I'm getting here `server-manager.js` `getServer(textEditor: atom$TextEditor, projectPath?: string): ?ActiveServer` where there is active server for project and hence the message is sent.

**Comment by damieng** [comment]
All of our IDE UI is based on scopes rather than filenames.  

The two options would be:

1. Handle it cleanly in the language server and just return null (preferred)
2. Intercept things by overriding autolanguageclient behavior
3. Possibly adding file-specific grammar for manifest.yml

Is there any reason the language server can't just return null for things it doesn't understand? (Item 1)

It would potentially be possible for us to provide an additional file matching filter in autolanguageclient that every single provider gets routed through but that does make things a bit messier everywhere.

**Comment by BoykoAlex** [comment]
The server returns empty contents. Think shouldn't be a problem to return null either. My concern was that the server receives the message it shouldn't. This is not a blocking issue for my server at all. Just a minor thing I've noticed.

**Comment by damieng** [comment]
Let's go with that for now - if it starts being a perf/maintenance problem we'll put an extra method in that package authors can override with path specific filtering.
