### ISSUE TITLE
Provide better support for triggering AutoComplete

### ISSUE THREAD

**Issue by damieng** [atom/atom-languageclient#89]
Right now we try and call textDocument/complete for every single keystroke as that is how autocomplete-plus works.

This is too expensive for many language servers (e.g. ide-typescript) and instead we need some idea of when to trigger and the ability to filter client-side in memory, e.g.

1. Request textDocument/complete when '.' is typed or ctl-space (manual trigger)
2. If the results were isComplete true then client-side filter using fuzzaldrin for further typing
3. If the results were isComplete false then call textDocument/complete again with further typing
4. Correctly handle backspace in scenarios 2-3

A version of this without isComplete handling is currently hacked into ide-typescript at https://github.com/atom/ide-typescript/blob/master/lib/main.js#L19

**Comment by hansonw** [comment]
We have a version of this exact idea over at https://github.com/facebook/nuclide/blob/master/pkg/commons-atom/AutocompleteCacher.js, if you need to steal anything :P

**Comment by rcjsuen** [comment]
Seems to me like `textDocument/complete` requests should only be sent when manually triggered or when one of the `triggerCharacters` as defined by `serverCapabilities.completionProvider` are hit.

**Comment by damieng** [comment]
Yes, that is correct. Have worked around this in the typescript provider but need to build this into the language client library directly.

**Comment by deankevorkian** [comment]
In the current state, with the hack in ide-typescript, the client-side filter is done by the ide-* package, and has full control on updating the `server.currentSuggestions`. 
Since we want to move things to the atom language client, who's going to be in charge of editing the currentSuggestions? 
since the fuzzy filtering will be done in the languageclient package, and there's no logic for the ide-* to take part in,  the suggestions should be modified right after the filtering is done, by the languageclient itself. 
On the other hand, if we're calling `textDocument/complete`, we don't want the languageclient to modify server.currentSuggestions and instead, only resolve the returned suggestions from the LSP client - because the ide-typescript package, for example, might want to control it - maybe ranking suggestions by some config parameters (show variables before methods) etc.

To avoid inconsistency I think the languageclient should never modify the currentSuggestions, only resolve suggestions for the ide-* package. But this means the ide-* will **always** have to modify the `server.currentSuggestions` - even if no results were returned. does this make sense?

**Comment by damieng** [comment]
Checked in.
