### ISSUE TITLE
Choice to use alternate plugins for capabilities

### ISSUE THREAD

**Issue by jonyeezs** [atom/atom-languageclient#97]
I think it's a great idea that atom is planning to support LSP.

It would be nice if the atom-languageclient isn't so coupled to the nuclide's UIs.

Would it serve the idea of Atom being hackable if this package was moreso a middleware to facilitate the use with any other Atom plugins (eg. steelbrain's plugins).

**Comment by hansonw** [comment]
Actually atom-languageclient is already compatible with the steelbrain
indie linter API - it's just that there aren't standardized UIs for the
other LSP features yet.

Also, the "Nuclide UIs" are now published under "atom-ide-ui" so you no
longer have to install all of Nuclide.

Finally, we'll be thoroughly documenting all the services provided by
atom-ide-ui so that other plugins can work with atom-languageclient in the
same way :)

**Comment by damieng** [comment]
Hanson is totally correct. Any package that wants to implement the same services as atom-ide-ui can of course be used as plug-in replacements if you so wish,
